-- Migration: create orders table for Mercado Pago + Supabase flow.
-- Strategy: manual versioned SQL (DEC-012). Review before applying manually.
-- This file must not contain secrets, credentials, customer data, orders, or payments.

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  external_reference text not null unique,
  product_name text not null,
  quantity integer not null,
  amount numeric not null,
  currency text not null,
  status text not null default 'pending',
  mercadopago_payment_id text,
  mercadopago_status text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint orders_status_check check (status in ('pending', 'paid')),
  constraint orders_amount_check check (amount > 0)
);

comment on table public.orders is
  'Internal orders created by the backend before Mercado Pago checkout.';

comment on column public.orders.external_reference is
  'Unique internal reference used to correlate the order with Mercado Pago.';

comment on column public.orders.status is
  'Allowed values for the current implementation: pending, paid.';

comment on column public.orders.mercadopago_payment_id is
  'Mercado Pago payment identifier stored only after backend confirmation.';

-- external_reference already has an implicit unique index from the UNIQUE constraint.
create index if not exists orders_status_idx
  on public.orders (status);

create index if not exists orders_mercadopago_payment_id_idx
  on public.orders (mercadopago_payment_id);

-- Enable Row Level Security. No policies are created for anon or authenticated,
-- so public clients are blocked by default.
alter table public.orders enable row level security;

-- The backend uses SUPABASE_SERVICE_ROLE_KEY from server-side environment only.
-- Never expose that key to the frontend or browser. In Supabase, service_role
-- is privileged and can bypass RLS; keep it restricted to trusted backend code.
