-- Migration: create order_items and an atomic order + items RPC.
-- Apply manually only after explicit authorization.
-- This migration does not backfill or modify historical orders.
--
-- Required precondition in the target database:
--   select gen_random_uuid();
--
-- gen_random_uuid() must exist before this migration is applied. Do not install
-- uuid-ossp solely for this migration; current PostgreSQL exposes this function
-- natively. Verify the actual target environment before applying this file.

begin;

create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null,
  product_sku text not null,
  product_name text not null,
  product_size text,
  quantity integer not null,
  unit_price numeric(12, 2) not null,
  line_total numeric(12, 2)
    generated always as (quantity::numeric * unit_price) stored,
  created_at timestamptz not null default now(),

  constraint order_items_order_id_fk
    foreign key (order_id)
    references public.orders(id)
    on delete cascade,

  constraint order_items_product_sku_not_blank
    check (btrim(product_sku) <> ''),

  constraint order_items_product_name_not_blank
    check (btrim(product_name) <> ''),

  constraint order_items_product_size_not_blank
    check (product_size is null or btrim(product_size) <> ''),

  constraint order_items_product_size_length
    check (product_size is null or char_length(product_size) <= 20),

  constraint order_items_quantity_positive
    check (quantity > 0),

  constraint order_items_unit_price_positive
    check (unit_price > 0),

  constraint order_items_line_total_positive
    check (line_total > 0)
);

comment on table public.order_items is
  'Authoritative product and variant snapshots belonging to an internal order.';

comment on column public.order_items.order_id is
  'Internal order owner. Items are deleted if their order is deleted.';

comment on column public.order_items.product_sku is
  'Authoritative catalog SKU captured at purchase time.';

comment on column public.order_items.product_name is
  'Product name snapshot for historical display; never used as an identifier.';

comment on column public.order_items.product_size is
  'Optional variant size snapshot. Products without size use null.';

comment on column public.order_items.unit_price is
  'Authoritative unit price captured by the backend at purchase time.';

comment on column public.order_items.line_total is
  'Generated value equal to quantity multiplied by unit_price.';

create index order_items_order_id_idx
  on public.order_items (order_id);

create index order_items_product_sku_idx
  on public.order_items (product_sku);

alter table public.order_items enable row level security;

revoke all on table public.order_items
  from public, anon, authenticated;

grant select, insert on table public.order_items
  to service_role;

-- SECURITY INVOKER requires the backend role to retain access to the parent
-- order table. These grants do not expose either table to public roles.
grant select, insert on table public.orders
  to service_role;

-- Resolve identity sequences from PostgreSQL metadata instead of assuming
-- their generated names. Dynamic SQL is used only during this migration for
-- identifier-safe GRANT statements; the runtime RPC contains no dynamic SQL.
do $sequence_grants$
declare
  target_sequence text;
begin
  foreach target_sequence in array array[
    pg_get_serial_sequence('public.orders', 'id'),
    pg_get_serial_sequence('public.order_items', 'id')
  ]
  loop
    if target_sequence is null then
      raise exception using
        errcode = '55000',
        message = 'required identity sequence was not found';
    end if;

    execute format(
      'grant usage, select on sequence %s to service_role',
      target_sequence::regclass
    );
  end loop;
end;
$sequence_grants$;

create function public.create_pending_order_with_items(
  p_expected_amount numeric,
  p_currency text,
  p_customer_first_name text,
  p_customer_last_name text,
  p_customer_email text,
  p_customer_phone text,
  p_shipping_province text,
  p_shipping_locality text,
  p_shipping_postal_code text,
  p_shipping_street text,
  p_shipping_street_number text,
  p_shipping_apartment text,
  p_shipping_notes text,
  p_items jsonb
)
returns table (
  order_id bigint,
  external_reference text,
  amount numeric,
  currency text,
  status text
)
language plpgsql
security invoker
set search_path = pg_catalog, public
as $function$
declare
  created_order public.orders%rowtype;
  raw_item jsonb;
  first_item jsonb;
  calculated_amount numeric;
  generated_external_reference text;
  quantity_numeric numeric;
  unit_price_numeric numeric;
begin
  if p_items is null or jsonb_typeof(p_items) <> 'array' then
    raise exception using
      errcode = '22023',
      message = 'items must be a JSON array';
  end if;

  if jsonb_array_length(p_items) < 1 then
    raise exception using
      errcode = '22023',
      message = 'order requires at least one item';
  end if;

  if jsonb_array_length(p_items) > 50 then
    raise exception using
      errcode = '22023',
      message = 'order has too many items';
  end if;

  if p_currency is null or btrim(p_currency) <> 'ARS' then
    raise exception using
      errcode = '22023',
      message = 'invalid currency';
  end if;

  if p_expected_amount is null
     or p_expected_amount <= 0
     or round(p_expected_amount, 2) <> p_expected_amount
     or p_expected_amount > 9999999999.99 then
    raise exception using
      errcode = '22023',
      message = 'invalid expected amount';
  end if;

  if p_customer_first_name is null
     or char_length(btrim(p_customer_first_name)) not between 2 and 60
     or btrim(p_customer_first_name)
        !~ '^[[:alpha:]][[:alpha:] ''-]*$' then
    raise exception using
      errcode = '22023',
      message = 'invalid customer data';
  end if;

  if p_customer_last_name is null
     or char_length(btrim(p_customer_last_name)) not between 2 and 60
     or btrim(p_customer_last_name)
        !~ '^[[:alpha:]][[:alpha:] ''-]*$' then
    raise exception using
      errcode = '22023',
      message = 'invalid customer data';
  end if;

  if p_customer_email is null
     or char_length(btrim(p_customer_email)) not between 5 and 254
     or btrim(p_customer_email)
        !~ '^[^[:space:]@]+@[^[:space:]@]+[.][^[:space:]@]+$' then
    raise exception using
      errcode = '22023',
      message = 'invalid customer data';
  end if;

  if p_customer_phone is null
     or p_customer_phone !~ '^[0-9]{10,15}$' then
    raise exception using
      errcode = '22023',
      message = 'invalid customer data';
  end if;

  if p_shipping_province is null
     or upper(btrim(p_shipping_province)) not in (
       'AR-A', 'AR-B', 'AR-C', 'AR-D', 'AR-E', 'AR-F',
       'AR-G', 'AR-H', 'AR-J', 'AR-K', 'AR-L', 'AR-M',
       'AR-N', 'AR-P', 'AR-Q', 'AR-R', 'AR-S', 'AR-T',
       'AR-U', 'AR-V', 'AR-W', 'AR-X', 'AR-Y', 'AR-Z'
     ) then
    raise exception using
      errcode = '22023',
      message = 'invalid delivery data';
  end if;

  if p_shipping_locality is null
     or char_length(btrim(p_shipping_locality)) not between 2 and 80 then
    raise exception using
      errcode = '22023',
      message = 'invalid delivery data';
  end if;

  if p_shipping_postal_code is null
     or upper(btrim(p_shipping_postal_code))
        !~ '^([0-9]{4}|[A-Z][0-9]{4}[A-Z]{3})$' then
    raise exception using
      errcode = '22023',
      message = 'invalid delivery data';
  end if;

  if p_shipping_street is null
     or char_length(btrim(p_shipping_street)) not between 2 and 100 then
    raise exception using
      errcode = '22023',
      message = 'invalid delivery data';
  end if;

  if p_shipping_street_number is null
     or char_length(btrim(p_shipping_street_number)) not between 1 and 12 then
    raise exception using
      errcode = '22023',
      message = 'invalid delivery data';
  end if;

  if p_shipping_apartment is not null
     and char_length(btrim(p_shipping_apartment)) > 30 then
    raise exception using
      errcode = '22023',
      message = 'invalid delivery data';
  end if;

  if p_shipping_notes is not null
     and char_length(btrim(p_shipping_notes)) > 250 then
    raise exception using
      errcode = '22023',
      message = 'invalid delivery data';
  end if;

  for raw_item in
    select value
    from jsonb_array_elements(p_items)
  loop
    if jsonb_typeof(raw_item) <> 'object' then
      raise exception using
        errcode = '22023',
        message = 'each item must be an object';
    end if;

    if exists (
      select 1
      from jsonb_object_keys(raw_item) as item_key
      where item_key not in (
        'product_sku',
        'product_name',
        'product_size',
        'quantity',
        'unit_price'
      )
    ) then
      raise exception using
        errcode = '22023',
        message = 'item contains unknown properties';
    end if;

    if not (
      raw_item ?& array[
        'product_sku',
        'product_name',
        'quantity',
        'unit_price'
      ]
    ) then
      raise exception using
        errcode = '22023',
        message = 'item is missing required properties';
    end if;

    if jsonb_typeof(raw_item->'product_sku') <> 'string'
       or jsonb_typeof(raw_item->'product_name') <> 'string'
       or jsonb_typeof(raw_item->'quantity') <> 'number'
       or jsonb_typeof(raw_item->'unit_price') <> 'number' then
      raise exception using
        errcode = '22023',
        message = 'item has invalid property types';
    end if;

    if raw_item ? 'product_size'
       and jsonb_typeof(raw_item->'product_size') not in ('string', 'null') then
      raise exception using
        errcode = '22023',
        message = 'item has invalid size type';
    end if;

    if char_length(btrim(raw_item->>'product_sku')) not between 2 and 64
       or btrim(raw_item->>'product_sku') !~ '^[A-Z0-9][A-Z0-9-]*$' then
      raise exception using
        errcode = '22023',
        message = 'invalid item SKU';
    end if;

    if char_length(btrim(raw_item->>'product_name')) not between 1 and 120 then
      raise exception using
        errcode = '22023',
        message = 'invalid item name';
    end if;

    if raw_item ? 'product_size'
       and jsonb_typeof(raw_item->'product_size') = 'string'
       and (
         char_length(btrim(raw_item->>'product_size')) < 1
         or char_length(btrim(raw_item->>'product_size')) > 20
       ) then
      raise exception using
        errcode = '22023',
        message = 'invalid item size';
    end if;

    quantity_numeric := (raw_item->>'quantity')::numeric;

    if quantity_numeric <> trunc(quantity_numeric)
       or quantity_numeric <= 0
       or quantity_numeric > 2147483647 then
      raise exception using
        errcode = '22023',
        message = 'invalid item quantity';
    end if;

    unit_price_numeric := (raw_item->>'unit_price')::numeric;

    if unit_price_numeric <= 0
       or round(unit_price_numeric, 2) <> unit_price_numeric
       or unit_price_numeric > 9999999999.99 then
      raise exception using
        errcode = '22023',
        message = 'invalid item unit price';
    end if;
  end loop;

  select sum(typed_item.quantity::numeric * typed_item.unit_price)
  into calculated_amount
  from jsonb_to_recordset(p_items) as typed_item (
    product_sku text,
    product_name text,
    product_size text,
    quantity integer,
    unit_price numeric
  );

  if calculated_amount is null
     or calculated_amount <= 0
     or calculated_amount > 9999999999.99 then
    raise exception using
      errcode = '22023',
      message = 'invalid calculated amount';
  end if;

  if calculated_amount <> p_expected_amount then
    raise exception using
      errcode = '22023',
      message = 'order amount does not match items';
  end if;

  first_item := p_items->0;
  generated_external_reference :=
    'LEMONT-ORDER-' || gen_random_uuid()::text;

  insert into public.orders (
    external_reference,
    product_name,
    product_sku,
    product_size,
    quantity,
    amount,
    currency,
    status,
    customer_first_name,
    customer_last_name,
    customer_email,
    customer_phone,
    shipping_country_code,
    shipping_province,
    shipping_locality,
    shipping_postal_code,
    shipping_street,
    shipping_street_number,
    shipping_apartment,
    shipping_notes
  )
  values (
    generated_external_reference,
    btrim(first_item->>'product_name'),
    btrim(first_item->>'product_sku'),
    case
      when jsonb_typeof(first_item->'product_size') = 'string'
        then btrim(first_item->>'product_size')
      else null
    end,
    (first_item->>'quantity')::integer,
    calculated_amount,
    'ARS',
    'pending',
    btrim(p_customer_first_name),
    btrim(p_customer_last_name),
    lower(btrim(p_customer_email)),
    p_customer_phone,
    'AR',
    upper(btrim(p_shipping_province)),
    btrim(p_shipping_locality),
    upper(btrim(p_shipping_postal_code)),
    btrim(p_shipping_street),
    btrim(p_shipping_street_number),
    nullif(btrim(p_shipping_apartment), ''),
    nullif(btrim(p_shipping_notes), '')
  )
  returning *
  into created_order;

  insert into public.order_items (
    order_id,
    product_sku,
    product_name,
    product_size,
    quantity,
    unit_price
  )
  select
    created_order.id,
    btrim(typed_item.product_sku),
    btrim(typed_item.product_name),
    nullif(btrim(typed_item.product_size), ''),
    typed_item.quantity,
    typed_item.unit_price
  from jsonb_to_recordset(p_items) as typed_item (
    product_sku text,
    product_name text,
    product_size text,
    quantity integer,
    unit_price numeric
  );

  return query
  select
    created_order.id,
    created_order.external_reference,
    created_order.amount,
    created_order.currency,
    created_order.status;
end;
$function$;

comment on function public.create_pending_order_with_items(
  numeric,
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  jsonb
) is
  'Atomically creates one pending order and all validated order items. Backend only.';

revoke execute on function public.create_pending_order_with_items(
  numeric,
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  jsonb
) from public, anon, authenticated;

grant execute on function public.create_pending_order_with_items(
  numeric,
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  jsonb
) to service_role;

-- Refresh the PostgREST schema cache after the transaction commits.
notify pgrst, 'reload schema';

commit;
